export const data = [
  {
    "Year": "1964",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "10000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1965",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "15000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1966",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "17000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1967",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "20000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1968",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "22000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1969",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "22000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1970",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "20000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1975",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "2110",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1976",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "4000",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1977",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "14380",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1978",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "124210",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1979",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "397290",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1980",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "346928",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1981",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "312548",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1982",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "325343",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1983",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "328399",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1984",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "328095",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1985",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "326617",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1986",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "326668",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1987",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "325717",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1988",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "440379",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1989",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "456936",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1990",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "496029",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1991",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "498323",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1992",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "517111",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1993",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "527625",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1994",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "539095",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1995",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "543536",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1996",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "518335",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1997",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "476795",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "0"
  },
  {
    "Year": "1998",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "435437",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "45"
  },
  {
    "Year": "1999",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "405378",
    "Asylum-seekers": "0",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "38"
  },
  {
    "Year": "2000",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "370753",
    "Asylum-seekers": "1525",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "37"
  },
  {
    "Year": "2001",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "353211",
    "Asylum-seekers": "3471",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "2036"
  },
  {
    "Year": "2002",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "373732",
    "Asylum-seekers": "2092",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "1954"
  },
  {
    "Year": "2003",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "363170",
    "Asylum-seekers": "1247",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "1691"
  },
  {
    "Year": "2004",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "349793",
    "Asylum-seekers": "1075",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "1829"
  },
  {
    "Year": "2005",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "358268",
    "Asylum-seekers": "1699",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "797"
  },
  {
    "Year": "2006",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "374278",
    "Asylum-seekers": "1762",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "476"
  },
  {
    "Year": "2007",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "327770",
    "Asylum-seekers": "1775",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "165"
  },
  {
    "Year": "2008",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "328175",
    "Asylum-seekers": "1706",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "87"
  },
  {
    "Year": "2009",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "339299",
    "Asylum-seekers": "1191",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2010",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "338707",
    "Asylum-seekers": "1123",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2011",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "337828",
    "Asylum-seekers": "1304",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2012",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "336936",
    "Asylum-seekers": "1394",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2013",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "314109",
    "Asylum-seekers": "1999",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2014",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "313420",
    "Asylum-seekers": "3132",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2015",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "313152",
    "Asylum-seekers": "4373",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "265"
  },
  {
    "Year": "2016",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "329341",
    "Asylum-seekers": "4538",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2017",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "334064",
    "Asylum-seekers": "7115",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2018",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "334464",
    "Asylum-seekers": "5571",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2019",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "316441",
    "Asylum-seekers": "8095",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2020",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "316728",
    "Asylum-seekers": "9440",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  },
  {
    "Year": "2021",
    "Country of origin": "Viet Nam",
    "Country of origin (ISO)": "VNM",
    "Refugees under UNHCR's mandate": "317737",
    "Asylum-seekers": "10345",
    "IDPs of concern to UNHCR": "0",
    "Venezuelans displaced abroad": "",
    "Stateless persons": "0",
    "Others of concern": "68"
  }
]